name: CodeTime - Readme

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  update-readme:
    name: CodeTime's Graph in Readme
    runs-on: ubuntu-latest
    steps:
      - uses: xafec/codetime-readme@beta06
        with:
          INPUT_CODETIME_COOKIE_KEY: ${{ secrets.INPUT_CODETIME_COOKIE_KEY }}
          INPUT_USERNAME: "xafec"
          INPUT_GH_TOKEN: ${{ secrets.INPUT_GH_TOKEN }}
